# Generated by Django 2.2 on 2019-06-17 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('lang', models.CharField(max_length=100)),
                ('reader', models.CharField(max_length=100)),
                ('id_Playlist', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('files', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('publishing_house', models.CharField(max_length=100)),
                ('publish_year', models.DateField(max_length=100)),
                ('number_of_page', models.IntegerField()),
                ('isnb', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('img', models.ImageField(upload_to='user_img')),
                ('main_mp3', models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Plik audio')),
                ('dimensions', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Author')),
                ('genre', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='dictionary.Genre')),
                ('id_Audio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='books.Audio')),
                ('id_Edition', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Edition')),
                ('lang', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Languages')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Добавить книги',
            },
        ),
    ]
