# Generated by Django 2.2 on 2019-06-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('main_mp3', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Покубки',
                'verbose_name_plural': 'Покубки в корзине',
            },
        ),
    ]
